install.packages("ggplot2")
install.packages("archdata")
install.packages("RCurl")
install.packages("jsonlite")
install.packages("dplyr")
install.packages("rJava", repos='http://cran.us.r-project.org')
install.packages("tabulizer", repos='http://cran.us.r-project.org')
